Repository latentnetworks/vimure, pull requests merged in 2022-05, with the labels that each got.

#32 :sparkles: Generate X given Y and format roxygen2 docs
  src/R/NAMESPACE
  src/R/R/conversion.R
  src/R/R/generate_X.R
  src/R/R/synthetic.R
  src/R/R/zzz.R
  src/R/README.Rmd
  src/R/README.md
  src/R/man/DegreeCorrectedSBM.Rd
  src/R/man/StandardSBM.Rd
  src/R/man/build_X.Rd
  src/R/man/extract_Xavg.Rd
  src/R/man/extract_Y.Rd
  src/R/man/figures/README-unnamed-chunk-4-1.png
  src/R/man/gm_CReciprocity.Rd
  src/R/man/gm_DegreeCorrectedSBM.Rd
  src/R/man/gm_StandardSBM.Rd
  src/R/tests/testthat/test-generate_X.R
  src/R/tests/testthat/test-synthetic.R
  src/python/vimure/synthetic.py
Labels: documentation, enhancement

#36 🪓 Change the way we calculate X_union and X_intersection
  src/python/vimure/synthetic.py
Labels: bug

#39 :sparkles: Implement ViMuRe model
  notebooks/R/RMarkdown 1 -  Generate Synthetic Networks.Rmd
  notebooks/R/RMarkdown 2 - Run Model.Rmd
  notebooks/R/RMarkdown 3 - Karnataka Data.Rmd
  src/R/DESCRIPTION
  src/R/NAMESPACE
  src/R/R/conversion.R
  src/R/R/generate_X.R
  src/R/R/model.R
  src/R/R/synthetic.R
  src/R/R/utils.R
  src/R/R/zzz.R
  src/R/README.Rmd
  src/R/README.md
  src/R/man/build_X.Rd
  src/R/man/build_custom_theta.Rd
  src/R/man/figures/README-unnamed-chunk-2-1.png
  src/R/man/figures/README-unnamed-chunk-4-1.png
  src/R/man/overall_reciprocity.Rd
  src/R/man/parse_graph_from_csv.Rd
  src/R/man/parse_graph_from_edgelist.Rd
  src/R/man/parse_graph_from_igraph.Rd
  src/R/man/summary.vimure.model.VimureModel.Rd
  src/R/man/vimure.Rd
  src/R/tests/testthat/test-generate_X.R
  src/R/tests/testthat/test-model.R
  src/R/tests/testthat/test-utils.R
  src/python/vimure/diagnostics.py
  src/python/vimure/io.py
  src/python/vimure/model.py
  src/python/vimure/test/test_model.py
Labels: enhancement
